import type { Metadata } from "next";
import { Newsreader, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import SideCover from "../components/SideCover";
import { Providers } from "../components/providers/chakra-provider";
import { Flex } from "@chakra-ui/react";

const newsreader = Newsreader({
  subsets: ["latin"],
  variable: "--font-newsreader",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const butler = localFont({
  src: [
    {
      path: "../app/fonts/Butler.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../app/fonts/Butler-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../app/fonts/Butler-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-butler",
});

export const metadata: Metadata = {
  title: "The Wedding of Tiffany & Jared by Invitato",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${newsreader.variable} ${poppins.variable} ${butler.variable} antialiased relative`}
      >
        <Providers>
          <Flex>
            <SideCover />
            <main>{children}</main>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
